added mkdir spool/

diff --git a/secedgar/edgar-pull-daily b/secedgar/edgar-pull-daily
--- a/secedgar/edgar-pull-daily
+++ b/secedgar/edgar-pull-daily
@@ -1,9 +1,9 @@
 #!/bin/bash
 #
 #  Synopsis:
-#	Pull yesterday's edgar reports.
+#	Pull yesterday's edgar reports from www.sec.gov/Archives/edgar/Feed
 #  Usage:
-#	1 0 * * * * cd support/edgar; /usr/local/jmscott/bin/edgar-pull-daily
+#	13 2 * * * * cd support/edgar; /usr/local/jmscott/bin/edgar-pull-daily
 #
 
 log()
@@ -51,6 +51,13 @@ DAY=$(date -v '-1d' +'%d')
 log "report year: $YEAR"
 log "report month: $MONTH"
 log "report day: $DAY"
+
+if [ ! -d spool ];  then
+	log "dir does not exist: $(pwd)/spool"
+	mkdir -p spool || die "mkdir spool failed: exit status=$?"
+fi
+
+cd spool || die "cd spool failed: exit status=$?"
 
 QTR=QTR$(get_quarter $MONTH)
 log "report quarter: $QTR"
